### ISSUE TITLE
New name suggestion

### ISSUE THREAD

**Issue by austinkregel** [papyros/papyros#2]
Papyros is a trademarked name, I did some further digging and found the actual trademarked on the USPTO's website. The trademark is still active though, so a name change is recommended.  
`http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4807:ewndmh.2.1`
The company's actual website is here.
`http://www.system96.com/papyros/default.html`

Might I recommend one of the following `Parchment OS`, `Flat OS`, and `Maldivos (Material Design Operating System)`, all with no record at the USPTO.

**Comment by iBelieve** [comment]
It shouldn't matter as that Papyros is in a different trademark category, so from a legal standpoint we should be fine, and there shouldn't be any confusion either.
