### ISSUE TITLE
Cannot install papyros on Archlinux

### ISSUE THREAD

**Issue by huiyiqun** [papyros/papyros#24]
I try to install papyros on Archlinux refering [this page](http://papyros.io/download/) and pacman mentions me that `qt5-base` is reflected with `qt5-base-git`.

I try to replace `qt5-base` with `qt-base-git` but it failed.

```
error: failed to commit transaction (conflicting files)
qt5-base-git: /usr/bin/moc exists in filesystem
qt5-base-git: /usr/bin/qdbuscpp2xml exists in filesystem
qt5-base-git: /usr/bin/qdbusxml2cpp exists in filesystem
qt5-base-git: /usr/bin/qdoc exists in filesystem
qt5-base-git: /usr/bin/qlalr exists in filesystem
qt5-base-git: /usr/bin/qmake exists in filesystem
qt5-base-git: /usr/bin/rcc exists in filesystem
qt5-base-git: /usr/bin/uic exists in filesystem
Errors occurred, no packages were upgraded.
```

I find that `/usr/bin/moc` is owned by `qtchooser` which is dependency of `qt5-base` but optional dependency of `qt5-base-git`.

There must be an error in `PKGBUILD` of `qt5-base-git`. How about using the official `qt5-base`? It has been upgraded to 5.5.0.

**Comment by 29jm** [comment]
Just use --force to bypass the check for conflicting files.

**Comment by alexkreidler** [comment]
If you're still interested, you can now install it from the AUR

**Comment by huiyiqun** [comment]
I have installed the packages from repo of papyros which using the official qt5.
