### ISSUE TITLE
Why not a custom distribution?

### ISSUE THREAD

**Issue by ghost** [papyros/papyros#3]
It's nice to know that Papyros wishes to focus more on the user interface, but, to deliver the best user experience it would be better to have a fully integrated system, right from the base level up through to the user interface.

I have been quite gung-ho about working on the UI and applications using QML + JavaScript, but have come to realize that I could better contribute to work on Papyros by way of working on a custom designed and built GNU/Linux distribution.

I would appreciate Michael Spencer setting a general direction for the base system and others chipping in with their comments, suggestions and tips.

**Comment by iBelieve** [comment]
We're definitely building our own operating system (that's what this repo is for tracking progress on). We'll be using Arch, OSTree, and xdg-app to build a stable and user-friendly distro. I've answered a lot of questions on Google+, and just today collected links to various discussions and put them in our wiki [here](https://github.com/papyros/papyros/wiki/OS-Plans). I also have a FAQ page highlighting some goals about the OS: http://www.papyros.io/faq/.

We definitely would love you help building the base OS. Thanks for your interest.

**Comment by ghost** [comment]
Great.

My interest in Papyros is primarily because your vision for what you want to do with the project is quite interesting, secondarily, I have the experience by way of having done this before, and it would be fun to do it again with present day technologies.

A few questions;
Are you fixated on ArchLinux? if yes, why?
Would you consider a LFS effort using 'opkg' as the package management system?
What would be the preliminary areas of concern for the base OS?
What kind of functionality would you expect from the base OS? Performance. Security. Simplicity.
What is the bare minimum you would expect from the base OS?
Would you like to term the base OS as "Papyros Core"?

Let's take this step by step so that we can attain clarity on what we are doing, and why we are doing it that way, this will benefit Papyros in the long term.

Fair?

**Comment by iBelieve** [comment]
Here are answers to your questions:
- Yes, unless it can be shown that LFS or another distro would provide a better base OS. Arch is simple, has no default desktop environment or other features we don't need, has a simple packaging format, and tries to stay as close to upstream as possible. All we need it a base OS to bootstrap our OSTree images; we won't use pacman from an end-user perspective
- LFS seems like a lot of work that Arch already does for us, allowing us to focus on the end-user experience. I see no reason to do things ourself unless it provides us with enough benefits
- The primary goals/concerns initially is going to be getting OSTree working and handling things like installation, drivers, and app installation using xdg-app
- Primary functionality will be security, stability, and atomic upgrades via OSTree. The root filesystem will be readonly and upgrades are atomic, keeping the user safe and preventing him from worrying about messing up the system.
- Bare minimum would be OSTree, system upgrades, app installation via xdg-app. App runtimes (Material, GNOME, KDE, etc) will be installed as xdg-app runtimes.
- I like the idea of a "Papyros Core", focusing on building an OSTree layer on top of Arch. Then with a simple config script, we can set up the packages necessary for a full Papyros system with the Papyros desktop shell, login screen, etc.

Hope that answers your questions.

**Comment by ghost** [comment]
Yes, you have answered my questions, and have concluded that "Papyros Core" should be LFS based.
Why LFS? because (for me) starting from scratch would be a lot simpler than spending time trying to understand a pre-built system like ArchLinux.
I will also look into getting OSTree and xdg-app working on the "Papyros Core" system.

**Comment by iBelieve** [comment]
That's not a good enough reason. Maintaining an entire distribution and all its packages in a huge task, and Arch is already doing a great job at it. Arch is simple enough to learn, and is what we'll be using unless there is a solid reason to switch, that is what we will be sticking with.

**Comment by ghost** [comment]
Sounds fair.
I am going to build my custom GNU/Linux distribution any ways.
Once done, I'll set it up for review by the Papyros team, if found suitable, you can use it, else I'll layer my distribution with your UI and take it in a direction I feel fit.

**Comment by iBelieve** [comment]
Closing as we are currently committed to building an OSTree-based operating system for Papyros using an Arch Linux base OS. Please reopen if you have any further reasons why we should use a custom distro.
