### ISSUE TITLE
Demo shows Radio buttons not centered

### ISSUE THREAD

**Issue by ghost** [papyros/papyros#4]
The radio buttons in the latest demo (as shown in the screenshot) aren't centered.
![screenshot from 2015-01-24 22 13 01](https://cloud.githubusercontent.com/assets/10281664/5888060/736c3108-a416-11e4-9cb0-f79861661ec4.png)

**Comment by iBelieve** [comment]
This is the wrong project to file issues for the Material Design framework. If this is still a bug, please file a new bug under [papyros/qml-material](https://github.com/papyros/qml-material).
