### ISSUE TITLE
Switch buttons aren't anti-aliased

### ISSUE THREAD

**Issue by ghost** [papyros/papyros#5]
The switch buttons as shown below from the latest demo aren't anti-aliased, i.e. the round buttons appear to have unsmooth peripheri.

![screenshot from 2015-01-24 22 23 55](https://cloud.githubusercontent.com/assets/10281664/5888111/e0314d68-a417-11e4-8a53-b6a9a4601633.png)

**Comment by iBelieve** [comment]
This is the wrong project to file issues for the Material Design framework. If this is still a bug, please file a new bug under [papyros/qml-material](https://github.com/papyros/qml-material).
