### ISSUE TITLE
Ripple effect not expanding over the whole item

### ISSUE THREAD

**Issue by David96** [papyros/papyros#7]
When clicking and holding something the ripple effect doesnt cover the whole item (which it does in Android). the radius of the used circle is probably calculated as half the width of the element while it should be a bit more than the width to fully cover the item, see screenshot.
![papyros-bug](https://cloud.githubusercontent.com/assets/5256992/6018860/70df7752-ab9a-11e4-86ba-e3c84d8bf8b8.png)

**Comment by iBelieve** [comment]
This was fixed in a recent update to the Ink effect. In the future, please file bugs like this in the material design framework repository, https://github.com/papyros/qml-material. Thanks!
