### ISSUE TITLE
Please change .gitmodules so that it works in chroots

### ISSUE THREAD

**Issue by n3rdopolis** [papyros/papyros#8]
Hi. I don't know why the submodule checkout is not working in non-interactive scripts, as I get  

The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?  
during git submodule update 

It seems that the git@github.com: in .gitmodules needs to be changed to https://github.com/ and then it works in chroots.

Thanks.

**Comment by n3rdopolis** [comment]
I found that it's not just chroots. Any possibility the github URL can be changed so that the submodules can be cloned in non interactive scripts?

**Comment by SuicSoft** [comment]
Submit a pull request

**Comment by n3rdopolis** [comment]
seems that .gitmodules is dropped, this can probably be closed I think?

**Comment by SuicSoft** [comment]
Yes

**Comment by SuicSoft** [comment]
OK, closed
